"""remove user_id from positions

Revision ID: 155ecd849e07
Revises: aff8f7bf4c47
Create Date: 2026-05-31 16:35:00.940532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155ecd849e07'
down_revision: Union[str, Sequence[str], None] = 'aff8f7bf4c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('positions_user_id_fkey'), 'positions', type_='foreignkey')
    op.drop_column('positions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('positions_user_id_fkey'), 'positions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
