"""add name_pt and name_en to positions

Revision ID: 2fb4f33c5180
Revises: 293ac8cd768a
Create Date: 2026-05-31 16:05:04.685333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb4f33c5180'
down_revision: Union[str, Sequence[str], None] = '293ac8cd768a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('positions', sa.Column('name_en', sa.String(length=100), nullable=True))
    op.add_column('positions', sa.Column('name_pt', sa.String(length=100), nullable=True))
    
    op.execute("UPDATE positions SET name_en = name, name_pt = name WHERE name_en IS NULL")
    
    op.alter_column('positions', 'name_en', nullable=False)
    op.alter_column('positions', 'name_pt', nullable=False)
    op.drop_column('positions', 'name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('positions', 'name_pt')
    op.drop_column('positions', 'name_en')
    # ### end Alembic commands ###
