"""add name_en name_pt notes_en notes_pt to cards

Revision ID: aff8f7bf4c47
Revises: 2fb4f33c5180
Create Date: 2026-05-31 16:17:18.084535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff8f7bf4c47'
down_revision: Union[str, Sequence[str], None] = '2fb4f33c5180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('cards', sa.Column('name_en', sa.String(length=100), nullable=True))
    op.add_column('cards', sa.Column('name_pt', sa.String(length=100), nullable=True))
    op.add_column('cards', sa.Column('notes_en', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('notes_pt', sa.Text(), nullable=True))

    op.execute("UPDATE cards SET name_en = name, name_pt = name WHERE name_en IS NULL")
    op.execute("UPDATE cards SET notes_en = notes, notes_pt = notes WHERE notes_en IS NULL")

    op.alter_column('cards', 'name_en', nullable=False)
    op.alter_column('cards', 'name_pt', nullable=False)

    op.drop_column('cards', 'name')
    op.drop_column('cards', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('cards', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cards', 'notes_pt')
    op.drop_column('cards', 'notes_en')
    op.drop_column('cards', 'name_pt')
    op.drop_column('cards', 'name_en')
    # ### end Alembic commands ###
