"""add games table and game_id to deck

Revision ID: c43e4df1007a
Revises: f986d8a5818f
Create Date: 2026-06-01 22:46:23.311060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c43e4df1007a'
down_revision: Union[str, Sequence[str], None] = 'f986d8a5818f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cards', 'perspective',
               existing_type=postgresql.ENUM('top', 'bottom', 'neutral', name='cardperspective'),
               nullable=True,
               existing_server_default=sa.text("'neutral'::cardperspective"))
    op.add_column('deck', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deck', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deck', type_='foreignkey')
    op.drop_column('deck', 'game_id')
    op.alter_column('cards', 'perspective',
               existing_type=postgresql.ENUM('top', 'bottom', 'neutral', name='cardperspective'),
               nullable=False,
               existing_server_default=sa.text("'neutral'::cardperspective"))
    op.drop_table('games')
    # ### end Alembic commands ###
