"""move rusty and studying from cards to deck

Revision ID: d223a9e7988c
Revises: 155ecd849e07
Create Date: 2026-05-31 16:47:03.498207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd223a9e7988c'
down_revision: Union[str, Sequence[str], None] = '155ecd849e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'studying')
    op.drop_column('cards', 'rusty')
    op.add_column('deck', sa.Column('rusty', sa.Boolean(), nullable=True))
    op.add_column('deck', sa.Column('studying', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck', 'studying')
    op.drop_column('deck', 'rusty')
    op.add_column('cards', sa.Column('rusty', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('studying', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
