"""add Takedown and Pass to card_type enum

Revision ID: e70c8e25f85d
Revises: d223a9e7988c
Create Date: 2026-05-31 17:30:52.491904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70c8e25f85d'
down_revision: Union[str, Sequence[str], None] = 'd223a9e7988c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
